"""Hearts: lost on mistakes and given back one at a time every five hours.

Regeneration is computed lazily instead of by a background job. The anchor marks the start of
the running five-hour interval, and every read "settles" the state by crediting the whole
intervals that have passed since then.
"""

from dataclasses import dataclass
from datetime import datetime, timedelta

MAX_HEARTS = 5
REGEN = timedelta(hours=5)


@dataclass(frozen=True)
class HeartsState:
    hearts: int
    anchor: datetime | None  # start of the running regeneration interval; None when full

    def __post_init__(self) -> None:
        # The same invariant as the database CHECK: the clock only runs while hearts are missing.
        if not 0 <= self.hearts <= MAX_HEARTS:
            raise ValueError(f"hearts must be between 0 and {MAX_HEARTS}, got {self.hearts}")
        if (self.anchor is None) != (self.hearts == MAX_HEARTS):
            raise ValueError("anchor must be set exactly when hearts are below the maximum")


def settle_hearts(s: HeartsState, now: datetime) -> HeartsState:
    """Credit every heart regenerated by ``now``."""
    if s.anchor is None:
        return s
    intervals = (now - s.anchor) // REGEN  # whole intervals; negative if the clock went back
    if intervals <= 0:
        return s
    if s.hearts + intervals >= MAX_HEARTS:
        return refill_hearts()
    # Move the anchor by whole intervals only, so time already spent in the current
    # interval still counts towards the next heart.
    return HeartsState(s.hearts + intervals, s.anchor + intervals * REGEN)


def lose_heart(s: HeartsState, now: datetime) -> HeartsState:
    """Take one heart for a mistake. Losing one from full starts the regeneration clock."""
    settled = settle_hearts(s, now)
    if settled.hearts == 0:
        return settled
    if settled.hearts == MAX_HEARTS:
        return HeartsState(MAX_HEARTS - 1, now)
    return HeartsState(settled.hearts - 1, settled.anchor)


def gain_heart(s: HeartsState, now: datetime) -> HeartsState:
    """Give one heart (the practice reward) without restarting the regeneration clock."""
    settled = settle_hearts(s, now)
    if settled.hearts + 1 >= MAX_HEARTS:
        return refill_hearts()  # full again (or already was), so the clock stops
    return HeartsState(settled.hearts + 1, settled.anchor)


def refill_hearts() -> HeartsState:
    """Return full hearts, as after buying a refill."""
    return HeartsState(MAX_HEARTS, None)


def next_heart_at(s: HeartsState) -> datetime | None:
    """Return when the next heart arrives, or None when full. Pass a settled state."""
    return None if s.anchor is None else s.anchor + REGEN
